### ISSUE TITLE
foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by clarknelson** [nkl-kst/the-sports-db#20]
When I call `$this->client->list()->players($team->idTeam);` I am getting an exception with the above error message. I see a related issue, but I'm still getting this message for 1.0.2. I'm able to catch for my use case but thought you would want to know. I believe the team just does not have any players listed. 

Thanks,

**Comment by nkl-kst** [comment]
Hey Clark,

thanks for opening this issue. You are right, `list()->players(id)` should not throw an exception if there are no team members.

Could you tell me which ID you used? Thanks in advance.

**Comment by nkl-kst** [comment]
Fixed by #24

**Comment by clarknelson** [comment]
Thank you! sorry for no response, love your api
