### ISSUE TITLE
Should be null

### ISSUE THREAD

**Issue by MitchBred** [nkl-kst/the-sports-db#26]
![image](https://user-images.githubusercontent.com/33968202/123527498-73dfd780-d6e0-11eb-9417-015fb01d0181.png)

**Comment by nkl-kst** [comment]
Hey Mitchell,

thanks for opening this issue. Obviously, this should be fixed as soon as possible. This also broke the latest scheduled build: https://github.com/nkl-kst/the-sports-db/actions/runs/977588912

**Comment by nkl-kst** [comment]
Fixed in v1.0.5 (0fa346e)
