### ISSUE TITLE
Replace "honor" with "honour"

### ISSUE THREAD

**Issue by nkl-kst** [nkl-kst/the-sports-db#33]
According to the latest API changes, this library should also use the term "honour" instead of "honor".

- [x] Create class `Honour`, deperecate `Honor`
- [x] Create method `honours()` in `LookupEndpoint.php`, deprecate `honors()`
- [x] Rename all occurences of "honor" to "hounour" except of tests
- [x] Add new tests with usage of "honour" class and method

**Comment by zag2me** [comment]
Thanks, just came here to report this!

See here: https://www.thesportsdb.com/forum_topic.php?t=5559
