### ISSUE TITLE
Changed string for green icon

### ISSUE THREAD

**Issue by McAtze** [nkl-kst/the-sports-db#36]
There're some changes with the green thumb icon in /all_sports.php

It should be
```php
public ?string $strSportIconGreen;
```

![Bildschirmfoto 2022-08-14 um 12 16 37](https://user-images.githubusercontent.com/8874582/184532436-3188c9b6-2aae-438e-88b9-558a7e03a29e.png)

https://github.com/nkl-kst/the-sports-db/blob/2779c1a7b02c7671ba6290c9a31d0b3d649d819f/src/Entity/Sport.php#L11

**Comment by nkl-kst** [comment]
@McAtze fixed in v1.3.2, thank you!
