### ISSUE TITLE
LeagueDivision is INT not STRING

### ISSUE THREAD

**Issue by McAtze** [nkl-kst/the-sports-db#40]
Hi,

in src/Entity/League.php on line 15 you reference to `strDivision` but it should be `intDivision`

```php
    public ?string $strDivision;
```

![Bildschirmfoto 2022-09-11 um 15 23 42](https://user-images.githubusercontent.com/8874582/189529957-1707a3c3-2dfa-43ce-9249-e7bf889c6558.png)

**Comment by nkl-kst** [comment]
Hi @McAtze,

thanks for opening this issue, you're completely right. I'll fix it as soon as possible.

Cheers

**Comment by nkl-kst** [comment]
Fixed in `v1.3.4`, thanks again.
