### ISSUE TITLE
breaking changes

### ISSUE THREAD

**Issue by zag2me** [nkl-kst/the-sports-db#55]
For info, finally made some planned breaking changes:

Just a few field renames in the team table:

strTeamJersey --->> strKit
strTeamBadge --> strBadge
strTeamLogo --> strLogo
strTeamFanart1 -- > strFanart1
strTeamFanart2 -- > strFanart2
strTeamFanart3 -- > strFanart3
strTeamFanart4 -- > strFanart4
strTeamBanner --> strBanner
strStadiumLocation --> strLocation
intStadiumCapacity ❌
strStadiumDescription ❌
strStadiumThumb ❌

**Comment by nkl-kst** [comment]
@zag2me thanks for this info and sorry for the late response. I'll try to fix this without introducing breaking changes in the lib.

> intStadiumCapacity ❌
> strStadiumDescription ❌
> strStadiumThumb ❌

Where do I find these infos now? Because I'm using them heavily in my personal hobby project www.soccer-map.com.

**Comment by nkl-kst** [comment]
> Where do I find these infos now? Because I'm using them heavily in my personal hobby project [www.soccer-map.com](http://www.soccer-map.com).

I saw the new API endpoints:

- Search for Venue
- Venue Details by Id

I'll add these to this lib asap.

**Comment by zag2me** [comment]
Yep, there is also a lot of work on V2 of the API recently. Hopefully much cleaner now.

Still adding a few features though.

EDIT: We also store Coordinates for venues now, which you might find useful.
